version: "3"
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./docker:/docker-entrypoint-initdb.d

  redis:
    image: redis
    restart: always

  website:
    build: .
    depends_on:
      - mysql
      - redis
    restart: always
    environment:
      MYSQL_HOST: mysql
      MYSQL_SOCKET:
      MYSQL_PORT: 3306
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      REDIS_HOST: redis
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

  adminer:
    image: adminer:4.7.7-standalone
    depends_on:
      - mysql
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - 8080:8080

  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    restart: always
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
