default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV.fetch("MYSQL_HOST") { 'localhost' } %>
  username: <%= ENV.fetch("MYSQL_USERNAME") { 'exercism_v3' } %>
  password: <%= ENV.fetch("MYSQL_PASSWORD") { 'exercism_v3' } %>
  socket: <%= ENV.fetch("MYSQL_SOCKET") { '/tmp/mysql.sock' } %>
  port: <%= ENV.fetch("MYSQL_PORT") { nil } %>
  timeout: 5000
  variables:
    sql_mode: traditional

development:
  primary: &development-primary
    <<: *default
    database: exercism_v3_development
  dj: &development-dj
    <<: *default
    database: exercism_v3_dj_development
    migrations_paths: "db/dj_migrate"

development_docker:
  primary:
    <<: *development-primary
  dj:
    <<: *development-dj

test:
  primary:
    <<: *default
    database: exercism_v3_test
  dj:
    <<: *default
    database: exercism_v3_test
    migrations_paths: "db/dj_migrate"
