name: Deploy to Amazon ECS

env:
  aws_region: eu-west-2
  task_definition: .github/config/ecs-task-def.json
  container_name: webserver
  service_name: webservers
  cluster_name: webservers

  ecr_repository_rails: "webserver-rails"
  dockerfile_rails: "docker/rails.Dockerfile"

  ecr_repository_nginx: "webserver-nginx"
  dockerfile_nginx: "docker/nginx.Dockerfile"

  ecr_repository_anycable_go: "webserver-anycable-go"
  dockerfile_anycable_go: "docker/anycable-go.Dockerfile"

  # TODO: Move this to be a secret
  s3_bucket: "exercism-assets-staging"

on:
  push:
    branches:
      - master

  # TODO: Remove befor merging
  pull_request:
    branches:
      - master

jobs:
  push_rails:
    name: Push rails to ECR and upload assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.5
        continue-on-error: true
        with:
          key: docker-layer-caching-deploy-rails-{hash}
          restore-keys: docker-layer-caching-deploy-rails-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Login to Amazon ECR
        id: login_to_ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build_image
        env:
          ECR_REGISTRY: ${{ steps.login_to_ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ecr_repository_rails }}
          IMAGE_TAG: ${{ github.sha }}
          DOCKERFILE: ${{ env.dockerfile_rails }}
          IMAGE_NAME: "${{ steps.login_to_ecr.outputs.registry}}/${{ env.ecr_repository_rails }}:${{ github.sha }}"
        run: |
          # Build a docker container and push it to ECR
          docker build -t $IMAGE_NAME -f $DOCKERFILE .
          docker push $IMAGE_NAME

          # Retag this as the latest
          docker tag $IMAGE_NAME $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest

          # Retag it as website below because the : hurts us otherwise
          docker tag $IMAGE_NAME website
          echo "::set-output name=image::$IMAGE_NAME"

      - name: Copy assets from Dockerfile
        id: copy_assets
        env:
          IMAGE_NAME: "${{ steps.login_to_ecr.outputs.registry}}/${{ env.ecr_repository_rails }}:${{ github.sha }}"
        run: |
          docker cp website:/opt/exercism/website/current/public/packs assets
          ls assets

      - name: Upload assets to s3
        id: upload_assets
        uses: jakejarvis/s3-sync-action@7ed8b112447abb09f1da74f3466e4194fc7a6311
        with:
          args: --acl public-read
        env:
          AWS_S3_BUCKET: ${{ env.s3_bucket }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ env.aws_region }}
          SOURCE_DIR: "assets"

  push_nginx:
    name: Push nginx to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.5
        continue-on-error: true
        with:
          key: docker-layer-caching-deploy-nginx-{hash}
          restore-keys: docker-layer-caching-deploy-nginx-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Login to Amazon ECR
        id: login_to_ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build_image
        env:
          ECR_REGISTRY: ${{ steps.login_to_ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ecr_repository_nginx }}
          IMAGE_TAG: ${{ github.sha }}
          DOCKERFILE: ${{ env.dockerfile_nginx }}
        run: |
          # Build a docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          # Retag this as the latest
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

  push_anycable_go:
    name: Push anycable_go to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: satackey/action-docker-layer-caching@v0.0.5
        continue-on-error: true
        with:
          key: docker-layer-caching-deploy-anycable_go-{hash}
          restore-keys: docker-layer-caching-deploy-anycable_go-

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Login to Amazon ECR
        id: login_to_ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build_image
        env:
          ECR_REGISTRY: ${{ steps.login_to_ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ env.ecr_repository_anycable_go }}
          IMAGE_TAG: ${{ github.sha }}
          DOCKERFILE: ${{ env.dockerfile_anycable_go }}
        run: |
          # Build a docker container and push it to ECR
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -f $DOCKERFILE .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

          # Retag this as the latest
          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"

  deploy:
    name: Deploy to ECS
    # TODO: Check this has all steps
    needs: [push_rails, push_nginx, push_anycable_go]

    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.aws_region }}

      - name: Login to Amazon ECR
        id: login_to_ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Upload the definition for rails
        id: update_definition_for_rails
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ env.task_definition }}
          container-name: ${{ env.container_name }}
          image: "${{ steps.login_to_ecr.outputs.registry }}/${{ env.ecr_repository_rails }}:${{ github.sha }}"

      - name: Upload the definition for nginx
        id: update_definition_for_nginx
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          # TODO: Check this is whatever comes directly before
          task-definition: ${{ steps.update_definition_for_rails.outputs.task-definition }}
          container-name: ${{ env.container_name }}
          image: "${{ steps.login_to_ecr.outputs.registry }}/${{ env.ecr_repository_nginx }}:${{ github.sha }}"

      - name: Deploy Amazon ECS task definition
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          # TODO: Check this is the latest to run
          task-definition: ${{ steps.update_definition_for_nginx.outputs.task-definition }}
          service: ${{ env.service_name }}
          cluster: ${{ env.cluster_name }}
          wait-for-service-stability: true
